version: "3.8"

services:
  app:
    container_name: ig_server-dev
    image: ig_server-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app/src
    ports:
      - 5000:5000